name: Build Kernel MI6 (SUKISU+SUSFS)

on:
  workflow_dispatch:

env:
  KERNEL_REPO: https://github.com/mpaujiah-ctrl/android_kernel_xiaomi_msm8998
  KERNEL_BRANCH: lineage-22.2
  DEFCONFIG: sagit_defconfig
  ARCH: arm64

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install deps
        run: |
         sudo apt-get update
         sudo apt-get install -y bc bison flex libssl-dev libelf-dev \
            build-essential python3 python-is-python3 zip libdebuginfod1

      - name: Clone kernel source
        run: git clone --depth=1 -b ${{ env.KERNEL_BRANCH }} ${{ env.KERNEL_REPO }} kernel    

      - name: Get GCC toolchain (mvaisakh, GCC 7.5)
        run: |
          git clone --depth=1 -b gcc-master https://github.com/mvaisakh/gcc-arm64 toolchain/gcc64
          git clone --depth=1 -b gcc-master https://github.com/mvaisakh/gcc-arm toolchain/gcc32
          ln -sf aarch64-elf-objcopy toolchain/gcc64/bin/aarch64-elf-elfedit
          ln -sf arm-eabi-objcopy toolchain/gcc32/bin/arm-eabi-elfedit
     
      - name: Sediakan 'ld' polos → ld.lld (banyak sub-Makefile manggil ld tanpa prefix)
        run: |
          ln -sf ld.lld $GITHUB_WORKSPACE/toolchain/clang/bin/ld
      
      - name: Get SukiSU-Ultra + SUSFS (bukan KernelSU-Next)
        working-directory: kernel
        run: |
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
          git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu -b kernel-4.4 susfs4ksu || \
          git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu susfs4ksu

      - name: Ganti aarch64-elf-ld dengan ld.lld (vdso Makefile hardcode CROSS_COMPILE ld)
        run: |
          rm -f toolchain/gcc64/bin/aarch64-elf-ld
          ln -s $GITHUB_WORKSPACE/toolchain/clang/bin/ld.lld toolchain/gcc64/bin/aarch64-elf-ld
      
      - name: Build kernel (clang r416183b)
        working-directory: kernel
        run: |
          export PATH="$GITHUB_WORKSPACE/toolchain/clang/bin:$GITHUB_WORKSPACE/toolchain/gcc64/bin:$GITHUB_WORKSPACE/toolchain/gcc32/bin:$PATH"
          export LDFLAGS="-fuse-ld=lld"
          make O=out ARCH=${{ env.ARCH }} ${{ env.DEFCONFIG }}
          make O=out ARCH=${{ env.ARCH }} -j$(nproc) \
            CC=clang \
            LD=ld.lld \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-elf- \
            CROSS_COMPILE_ARM32=arm-eabi- \
            KCFLAGS="-fuse-ld=lld"
     
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-msm8998-ksun
          path: kernel/out/arch/arm64/boot/Image*
