name: Build Kernel MI6 (SUKISU+SUSFS)

on:
  workflow_dispatch:

env:
  KERNEL_REPO: https://github.com/mpaujiah-ctrl/android_kernel_xiaomi_msm8998
  KERNEL_BRANCH: lineage-22.2
  DEFCONFIG: sagit_defconfig
  ARCH: arm64

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Install deps
        run: |
         sudo apt-get update
         sudo apt-get install -y bc bison flex libssl-dev libelf-dev \
            build-essential python3 python-is-python3 zip libdebuginfod1

      - name: Clone kernel source
        run: git clone --depth=1 -b ${{ env.KERNEL_BRANCH }} ${{ env.KERNEL_REPO }} kernel    

      - name: Get Clang r416183b (tag terbukti jalan di boot.img referensi)
        run: |
          git clone --filter=blob:none --no-checkout --depth=1 \
            https://github.com/AOSPA/android_prebuilts_clang_host_linux-x86 toolchain/clang-src
          cd toolchain/clang-src
          git sparse-checkout init --cone
          git sparse-checkout set clang-r416183b
          git checkout
          mv clang-r416183b ../clang

      - name: Get SukiSU-Ultra + SUSFS (bukan KernelSU-Next)
        working-directory: kernel
        run: |
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
          git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu -b kernel-4.4 susfs4ksu || \
          git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu susfs4ksu

      - name: Build kernel (clang r416183b, sama seperti referensi)
        working-directory: kernel
        run: |
          export PATH="$GITHUB_WORKSPACE/toolchain/clang/bin:$PATH"
          make O=out ARCH=${{ env.ARCH }} ${{ env.DEFCONFIG }}
          make O=out ARCH=${{ env.ARCH }} -j$(nproc) \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-android- \
            CROSS_COMPILE_ARM32=arm-linux-androideabi-
     
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-msm8998-ksun
          path: kernel/out/arch/arm64/boot/Image*
